# This is the default format. 
#
title : GouDan-er
# tagline: Site Tagline
author : Wenyuan Yan
  # name :  Wenyuan Yan
  # email : llyanwenyuan@gmail.com
  # github : goudan-er
  # feedburner : feedname

name: GouDan-er
description: a Personal Blog, goudan-er will occasionally writes about things.
url: http://www.goudan-er.xyz

markdown: rdiscount
permalink: /:year/:month/:title/

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
paginate: 24

production_url : www.goudan-er.xyz

